apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: ${project.artifactId}
data:
  application.yml: |-
    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          show-details: always

    feign:
      hystrix:
        enabled: true