apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - name: ${project.artifactId}
          image: nortthon/feign-hystrix:latest