apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  namespace: ${project.artifactId}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      serviceAccountName: feign-hystrix
      containers:
        - name: ${project.artifactId}
          image: nortthon/${project.artifactId}:${git.commit.id.abbrev}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            privileged: false
          envFrom:
            - secretRef:
                name: ${project.artifactId}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace