apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${project.artifactId}
  namespace: ${project.artifactId}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${project.artifactId}-role
  namespace: ${project.artifactId}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${project.artifactId}-role-binding
  namespace: ${project.artifactId}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${project.artifactId}-role
subjects:
  - kind: ServiceAccount
    name: ${project.artifactId}
    namespace: ${project.artifactId}